add_ons:
  chrome: stable
language: ruby

rvm:
  - 2.3.7
  - 2.4.6
  - 2.5.5
  - rbx-2

gemfile:
  - gemfiles/rails_4_2.gemfile

env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite3

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.5.5
    - rvm: rbx-2

before_install:
  - sudo apt-get install chromium-chromedriver
  - google-chrome-stable --headless --disable-gpu
  - gem uninstall -i $(rvm gemdir)@global -ax bundler
  - gem install bundler -v 1.17.3

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - bundle exec bin/calagator new spec/dummy --dummy --database=$DB --postgres-username=postgres
  - travis_retry bundle exec rake app:db:migrate app:db:seed
  - travis_retry bundle exec rake app:sunspot:solr:start_with_waiting

script:
  - bundle exec rake spec --trace
cache: bundler
